import { useHead } from '@unhead/vue'
import { computed, unref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { baseRouteName } from '../router'

// Defined once in vite.config.js (shared with the sitemap/robots
// generator so the two can't disagree).
const SITE_URL = __SITE_URL__
const SITE_NAME = 'Underlaid'
// 1200x630 PNG social previews, one per language (LinkedIn ignores SVG).
// Regenerated by scripts/make-og-images.mjs — see that file.
const OG_IMAGES = {
  en: {
    url: `${SITE_URL}/og-image.png`,
    alt: 'Map of Paris and its inner suburbs shaded by cumulative environmental exposure score, 0 to 4 — Underlaid',
  },
  fr: {
    url: `${SITE_URL}/og-image-fr.png`,
    alt: "Carte de Paris et de la petite couronne colorée selon le score de cumul d'exposition environnementale, de 0 à 4 — Underlaid",
  },
}
const OG_IMAGE_WIDTH = '1200'
const OG_IMAGE_HEIGHT = '630'

/**
 * Per-route <head> metadata: title, description, OG/Twitter tags,
 * canonical link, and reciprocal hreflang alternates (en/fr/x-default).
 *
 * @param {{en: string, fr: string} | (() => {en: string, fr: string})} title
 * @param {{en: string, fr: string} | (() => {en: string, fr: string})} description
 * @param {string} [image] absolute or root-relative image URL
 * @param {(locale: string) => object} [jsonLd] schema.org object per locale, if this page has one
 */
export function useSeoMeta({ title, description, image, jsonLd }) {
  const { locale } = useI18n()
  const route = useRoute()
  const router = useRouter()

  const base = computed(() => baseRouteName(route.name))
  const enPath = computed(() => router.resolve({ name: base.value }).fullPath)
  const frPath = computed(() => router.resolve({ name: `${base.value}-fr` }).fullPath)
  const selfPath = computed(() => (locale.value === 'fr' ? frPath.value : enPath.value))

  const resolvedTitle = computed(() => {
    const value = typeof title === 'function' ? title() : title
    const localized = unref(value)
    return `${localized[locale.value]} | ${SITE_NAME}`
  })
  const resolvedDescription = computed(() => {
    const value = typeof description === 'function' ? description() : description
    const localized = unref(value)
    return localized[locale.value]
  })
  const resolvedImage = computed(() => image || OG_IMAGES[locale.value]?.url || OG_IMAGES.en.url)
  const resolvedImageAlt = computed(() => (OG_IMAGES[locale.value] || OG_IMAGES.en).alt)
  const selfUrl = computed(() => `${SITE_URL}${selfPath.value}`)

  useHead({
    title: resolvedTitle,
    htmlAttrs: { lang: locale },
    meta: [
      { name: 'description', content: resolvedDescription },
      { property: 'og:site_name', content: SITE_NAME },
      { property: 'og:title', content: resolvedTitle },
      { property: 'og:description', content: resolvedDescription },
      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: selfUrl },
      { property: 'og:image', content: resolvedImage },
      { property: 'og:image:type', content: 'image/png' },
      { property: 'og:image:width', content: OG_IMAGE_WIDTH },
      { property: 'og:image:height', content: OG_IMAGE_HEIGHT },
      { property: 'og:image:alt', content: resolvedImageAlt },
      { property: 'og:locale', content: computed(() => (locale.value === 'fr' ? 'fr_FR' : 'en_US')) },
      { property: 'og:locale:alternate', content: computed(() => (locale.value === 'fr' ? 'en_US' : 'fr_FR')) },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: resolvedTitle },
      { name: 'twitter:description', content: resolvedDescription },
      { name: 'twitter:image', content: resolvedImage },
      { name: 'twitter:image:alt', content: resolvedImageAlt },
    ],
    link: [
      { rel: 'canonical', href: selfUrl },
      { rel: 'alternate', hreflang: 'en', href: computed(() => `${SITE_URL}${enPath.value}`) },
      { rel: 'alternate', hreflang: 'fr', href: computed(() => `${SITE_URL}${frPath.value}`) },
      { rel: 'alternate', hreflang: 'x-default', href: computed(() => `${SITE_URL}${enPath.value}`) },
    ],
    script: jsonLd
      ? [
          {
            type: 'application/ld+json',
            innerHTML: computed(() => JSON.stringify(jsonLd(locale.value))),
          },
        ]
      : [],
  })
}

export { SITE_URL, SITE_NAME }
